version: '3.7'

services:
  ansible:
    build:
      context: ./modules
      dockerfile: Dockerfile.ansible
    volumes:
      - ${ANSIBLE}:/ansible:rw

  golang:
    build:
      context: ./modules
      dockerfile: Dockerfile.golang
    volumes:
      - ${GOLANG}:/golang:rw

  puppet:
    build:
      context: ./modules
      dockerfile: Dockerfile.puppet
    volumes:
      - ${PUPPET}:/puppet:rw

  terraform:
    build:
      context: ./modules
      dockerfile: Dockerfile.terraform
    volumes:
      - ${TERRAFORM}:/terraform:rw
