web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./config/php:/code:ro
        - ./config/nginx:/etc/nginx/conf.d:ro
        - ./${OUT_DIR}:/data:ro
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./config/php:/code:ro
        - ./${OUT_DIR}:/data:ro
